apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "basic-helm.fullname" . }}
  labels:
    {{- include "basic-helm.labels" . | nindent 4 }}
data:
  {{- toYaml .Values.envVars | nindent 2 }}
